import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import Navbar from '@/components/navbar'
import { ThemeProvider } from "@/components/theme-provider"
import Footer from '@/components/footer'
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PagePulse',
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`${nunito.className}  min-h-screen flex flex-col`}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Navbar />

        {children}
        {/* <Footer /> */}
        </ThemeProvider>
      </body>
      
    </html>
    </ClerkProvider>
  )
}